{ inputs, pkgs }:
# NOT YET WIRED INTO `checks`. This does not pass, and flake.nix says so where
# it would otherwise be listed. What works and what does not, so the next person
# does not rediscover it:
#
#   Works: the installer runs unattended, disko partitions and mounts /dev/vdb
#   with btrfs and an ESP, the generated flake evaluates offline -- resolving
#   locked github: inputs from the store by narHash, which #12 listed as an
#   open question and which is now answered yes.
#
#   Fails: nixos-install cannot build the installed system's toplevel with no
#   network. The seeded system-path IS present in the node's store; the
#   toplevel is not, because it differs from anything that can be seeded --
#   hardware-configuration.nix is generated by nixos-generate-config ON THE
#   TARGET, and its content is not knowable from outside the VM. So the last
#   handful of derivations must either be buildable offline from seeded build
#   inputs, or the test has to let them build.
#
# `nix run .#installer-vm` performs the same install WITH a network and does
# succeed end to end, bootloader and all. That is the harness to iterate in;
# this file is the hermetic version of it.
#
# Does the installer's *output* boot?
#
# Every other check here boots a system the test itself built. This one boots a
# disk: a partition table, a bootloader and a generated flake that
# nixarchy-install wrote, with nothing from the test's own store handed to the
# kernel. That is the only way to find out whether the thing a person ends up
# with actually starts.
#
# Two phases on one disk image.
#
#   installer  a normal test node standing in for the ISO. It has the install
#              package, a blank /dev/vdb, and the whole reference closure in
#              its store, because a test VM has no network and nixos-install
#              copies from wherever it can reach.
#
#   target     NOT a second node. A node boots through qemu's -kernel from the
#              store, which is exactly what must not happen: the point is the
#              bootloader the installer wrote. So the installer is shut down
#              and a machine is built by hand on the same qcow2, with OVMF,
#              the way nixpkgs' own nixos/tests/installer.nix does it.
#
# encrypt=no, deliberately. The layout defaults to LUKS and an encrypted target
# would stop at a passphrase prompt this test would have to type through on a
# screen it cannot reliably read. Which layout LUKS produces is what the disko
# check proves; this one proves the install flow. Narrowing it here is cheaper
# than an OCR anchor on a passphrase prompt.
let
  # hyprland does not follow nixpkgs, so its inputs are separate locked entries
  # and are needed to evaluate the generated flake. Collected rather than
  # listed: enumerating aquamarine, hyprlang, hyprutils and the rest by hand is
  # a list that goes stale on the next bump and fails as a network fetch inside
  # a VM that has no network.
  collectInputs =
    flake:
    [ flake.outPath ] ++ builtins.concatMap collectInputs (builtins.attrValues (flake.inputs or { }));

  inputPaths = pkgs.lib.unique (builtins.concatMap collectInputs (builtins.attrValues inputs));

  reference = inputs.self.nixosConfigurations.reference.config.system.build;

  # A fixed hash, not a plaintext password. `password=` makes the installer
  # call mkpasswd, which salts randomly -- so the installed toplevel would be a
  # different store path on every run and could never match anything seeded
  # here. This is "omarchy", on a disposable VM.
  passwordHash = "$6$rounds=100000$nixarchytestsalt$0PVDWmxAsp7Bl1nqmv9Nnvm5RG4KP7wQAZ4L6ULDJcmJvYQyLdDPSPBnk1LKtNCdlvHmDPKXQhcYW0m0FQ0lJ1";

  # The exact disko script the generated flake will evaluate to. The reference
  # host's is for /dev/vda -- its placeholder device -- and this test installs
  # to /dev/vdb, so they are different derivations and the VM would have to
  # build one with no network. Seeding it here is what the ISO does for the
  # whole closure in #15; the test meets the same requirement early.
  targetSystem =
    (inputs.nixpkgs.lib.nixosSystem {
      inherit (pkgs) system;
      specialArgs = { inherit inputs; };
      modules = [
        inputs.self.nixosModules.nixarchy
        inputs.home-manager.nixosModules.home-manager
        inputs.disko.nixosModules.disko
        (import ../installer/host.nix {
          hostname = "installed";
          username = "omarchy";
        })
        (import ../installer/disk-config.nix {
          device = "/dev/vdb";
          encrypt = false;
        })
        # Everything the generated configuration.nix adds. Without these the
        # seeded system is not the system that gets installed: system-path
        # differs, so nixos-install has to rebuild it, and with no network it
        # cannot fetch the inputs to do so. Keep this in step with
        # installer/template/configuration.nix -- a mismatch shows up as
        # "cannot build", which is a clear enough signal.
        {
          time.timeZone = "UTC";
          console.keyMap = "us";
          nixpkgs.config.allowUnfree = true;
          services.displayManager.autoLogin = {
            enable = false;
            user = "omarchy";
          };
          users.users.omarchy.hashedPassword = passwordHash;
        }
      ];
    }).config.system.build;

  # The same helper nixpkgs' own boot tests use to pick a qemu binary, rather
  # than hardcoding qemu-system-x86_64 and losing KVM.
  qemuCommon = import "${inputs.nixpkgs}/nixos/lib/qemu-common.nix" {
    inherit (pkgs) lib stdenv;
  };

  # Both pflash drives, not just the code one. Without unit=1 the firmware has
  # nowhere to keep EFI variables, and a machine that cannot write them is a
  # different machine from the one a person installs onto.
  targetCommand = pkgs.lib.concatStringsSep " " [
    (qemuCommon.qemuBinary pkgs.qemu_test)
    "-cpu max -m 4096 -smp 4"
    "-drive file=vm-state-installer/empty0.qcow2,if=virtio,werror=report"
    "-drive if=pflash,format=raw,unit=0,readonly=on,file=${pkgs.OVMF.firmware}"
    "-drive if=pflash,format=raw,unit=1,readonly=on,file=${pkgs.OVMF.variables}"
  ];
in
pkgs.testers.runNixOSTest {
  name = "nixarchy-install";

  nodes.installer =
    { ... }:
    {
      imports = [
        inputs.self.nixosModules.nixarchy
        inputs.home-manager.nixosModules.home-manager
      ];

      environment.systemPackages = [
        inputs.self.packages.${pkgs.system}.install
        pkgs.git
      ];

      nix.settings = {
        experimental-features = [
          "nix-command"
          "flakes"
        ];
        # There is no network. Saying so explicitly turns "tried to fetch" into
        # a clear failure rather than a timeout that reads like flakiness.
        substituters = pkgs.lib.mkForce [ ];
      };

      # The answers the wizard would have collected. device is the blank second
      # disk; /dev/vda is this node's own root.
      environment.etc."nixarchy/answers".text = ''
        device=/dev/vdb
        encrypt=no
        hostname=installed
        username=omarchy
        password_hash=${passwordHash}
        timezone=UTC
        keymap=us
      '';

      # Everything the install will copy or evaluate, already present: the test
      # meets the offline reality that the ISO phase will have to solve for
      # real. If something is missing it surfaces as a fetch attempt with no
      # network, which is a clearer failure than a silent download would be.
      system.extraDependencies = [
        reference.toplevel
        reference.diskoScript
        targetSystem.diskoScript
        targetSystem.toplevel
        # The installed machine is not byte-identical to the seeded one: the
        # generated configuration.nix adds a timezone, a keymap, autologin and
        # a password hash, so a handful of aggregation derivations differ and
        # have to be built with no network. These are their build inputs.
        #
        # system.includeBuildDependencies would cover it and is not usable
        # here: on a desktop this size the evaluation alone passed 3.4 GB
        # resident with no end in sight.
        # Measured, not guessed. `nix run .#installer-vm` performs the same
        # install with a network and reports what it fetches to build with:
        # 37 paths, 109 MiB, and they are all one of two things -- stdenv's
        # build environment, and disko's runtime deps. Everything else it
        # fetches (1849 paths, 4.6 GiB) is the target closure, which the
        # reference toplevel above already carries.
        pkgs.stdenv
        pkgs.stdenvNoCC
        pkgs.stdenv.cc
        pkgs.gnumake
        pkgs.gnutar
        pkgs.diffutils
        pkgs.patchelf
        pkgs.file
        pkgs.findutils
        pkgs.gawk
        pkgs.gnused
        pkgs.gnugrep
        pkgs.gzip
        pkgs.xz
        pkgs.bash
        pkgs.bashInteractive
        pkgs.coreutils
        pkgs.perl
        pkgs.python3
        pkgs.jq
      ]
      ++ inputPaths;

      virtualisation = {
        memorySize = 6144;
        cores = 4;
        # The installer refuses to run where /sys/firmware/efi does not exist,
        # and is right to -- the layout is an ESP with systemd-boot and there
        # is no BIOS path. A default test node boots through -kernel with no
        # firmware at all, so the node has to be given some.
        useEFIBoot = true;
        # The blank target, which appears as /dev/vdb.
        emptyDiskImages = [ 20480 ];
        # nixos-install copies the whole closure into the target, and the
        # default 1 GB store overlay is nowhere near enough.
        diskSize = 32768;
      };
    };

  enableOCR = true;

  testScript = ''
    installer.wait_for_unit("multi-user.target")

    # Is what was seeded actually here? extraDependencies is supposed to put
    # the reference and target closures in this store, and when nixos-install
    # decides to build system-path anyway the useful question is whether the
    # path is missing or merely different.
    print("seeded system-path outputs present:")
    print(installer.succeed("ls -d /nix/store/*-system-path 2>/dev/null | head -5 || echo NONE"))
    print("seeded toplevels present:")
    print(installer.succeed("ls -d /nix/store/*-nixos-system-* 2>/dev/null | head -5 || echo NONE"))

    # ---- install -------------------------------------------------------
    import time
    import subprocess
    started = time.time()
    print(installer.succeed(
        "nixarchy-install --answers /etc/nixarchy/answers 2>&1", timeout=1800))
    elapsed = int(time.time() - started)
    print(f"install_seconds={elapsed}")

    # Asserted from this side, while the target is still mounted: it localises
    # a failure to "the install" rather than "the boot", which are very
    # different bugs to chase.
    installer.succeed("test -d /mnt/etc/nixos/.git")
    installer.succeed("test -d /mnt/boot/EFI")
    print("install wrote a flake and an ESP")

    # The name emptyDiskImages produces for a node called "installer". Asserted
    # rather than assumed: if the driver ever changes it, the failure should say
    # so here and not as a qemu error about a missing file.
    installer.succeed("true")
    print(subprocess.run(["ls", "vm-state-installer"], capture_output=True, text=True).stdout)

    installer.shutdown()

    # ---- boot what was installed ---------------------------------------
    # A command string, not a dict: create_machine's signature is
    # (start_command: str, *, name, keep_machine_state) in current nixpkgs.
    target = create_machine("${targetCommand}", name="target")
    target.start()
    target.wait_for_unit("multi-user.target")
    print("the installed disk booted on its own bootloader")

    # ---- the desktop comes up ------------------------------------------
    target.wait_for_unit("display-manager.service")
    target.wait_until_succeeds("loginctl list-sessions | grep -q greeter")

    # A blank greeter would still accept the password, so assert something was
    # drawn. Retried rather than slept at: a fixed wait is a guess about how
    # fast the machine is, and the same guess was wrong twice already in this
    # repo's other tests.
    drawn = ""
    for attempt in range(10):
        target.sleep(4)
        target.screenshot("greeter")
        drawn = target.get_screen_text().strip()
        print(f"attempt {attempt}: greeter OCR {drawn!r}")
        if drawn:
            break
    assert drawn, "the greeter never drew anything in 40s"

    target.send_chars("omarchy\n")
    target.wait_until_succeeds(
        "journalctl -b -u display-manager --no-pager"
        " | grep -q 'Authentication for user .*omarchy.* successful'")
    target.wait_until_succeeds("systemctl is-active user@1000.service")
    target.wait_until_succeeds("pgrep -u 1000 -f Hyprland")
    print("the installed machine reaches a Hyprland session")

    # ---- the flake on disk is the user's -------------------------------
    target.succeed("git -C /etc/nixos rev-parse --is-inside-work-tree")
    for f in ["flake.nix", "flake.lock", "configuration.nix",
              "disk-config.nix", "nixarchy-apps.nix"]:
        target.succeed(f"test -s /etc/nixos/{f}")
    target.succeed("grep -q 'nixarchy-apps.nix' /etc/nixos/configuration.nix")
    print("/etc/nixos is a git repository holding the five generated files")

    # ---- Invariant 1 ---------------------------------------------------
    # If the flake evaluates to the same store path that is running, then every
    # path in its closure already exists and there is by definition nothing to
    # build. That is stronger than parsing "N derivations will be built", and
    # it does not depend on the wording of Nix's output, which is not a stable
    # interface.
    #
    # Deliberately nixos-rebuild and not `nh os switch`, which is what a user
    # types: nh wraps nixos-rebuild, so asserting through it would test the
    # wrapper rather than the invariant. Do not tidy this up.
    before = target.succeed("readlink -f /run/current-system").strip()
    target.succeed("cd /etc/nixos && nixos-rebuild build --flake .#installed 2>&1 | tail -20")
    built = target.succeed("readlink -f /etc/nixos/result").strip()

    if built != before:
        print(target.succeed(
            "cd /etc/nixos && nix build --dry-run "
            ".#nixosConfigurations.installed.config.system.build.toplevel 2>&1 || true"))
    assert built == before, (
        f"a rebuild of the generated flake evaluates to {built}, not the "
        f"installed {before}: the flake on disk does not describe the machine "
        "it was installed on (Invariant 1).")

    target.succeed("cd /etc/nixos && nixos-rebuild switch --flake .#installed")
    assert target.succeed("readlink -f /run/current-system").strip() == before
    print("a rebuild straight after install builds nothing (Invariant 1)")
  '';
}
